export const APP = {
  INITIALIZED: 'APP_INITIALIZED'
}

export const AUTH = {
  REQUEST_START: 'AUTH_REQUEST_START',
  REQUEST_END: 'AUTH_REQUEST_END',
  LOGIN: 'AUTH_LOGIN',
  LOGOUT: 'AUTH_LOGOUT',
  FETCH_PROFILE: 'AUTH_FETCH_PROFILE'
}

export const AUTHORS = {
  REQUEST_START: 'AUTHORS_REQUEST_START',
  REQUEST_END: 'AUTHORS_REQUEST_END',
  FETCH_SUCCESS: 'AUTHORS_FETCH_SUCCESS',
  CREATE_SUCCESS: 'AUTHORS_CREATE_SUCCESS',
  UPDATE_SUCCESS: 'AUTHORS_UPDATE_SUCCESS',
  DELETE_SUCCESS: 'AUTHORS_DELETE_SUCCESS',
  CLEAR_ALL: 'AUTHORS_CLEAR_ALL'
}
