export const APP = {
  INITIALIZED: 'APP_INITIALIZED'
}

export const AUTH = {
  REQUEST_START: 'AUTH_REQUEST_START',
  REQUEST_END: 'AUTH_REQUEST_END',
  LOGIN: 'AUTH_LOGIN',
  LOGOUT: 'AUTH_LOGOUT',
  FETCH_PROFILE: 'AUTH_FETCH_PROFILE'
}
